import { Decimal } from "@prisma/client/runtime/library";

export function createInvoiceEmail(invoice: {
  id: string;
  number: string;
  currency: string;
  total: number | Decimal;
  client?: { name?: string | null; email?: string | null };
  user?: { 
    name?: string | null;
    settings?: {
      companyName?: string | null;
    } | null;
  };
}) {
  const appUrl =
    process.env.NEXT_PUBLIC_APP_URL || process.env.NEXTAUTH_URL || "";
  const base = appUrl.replace(/\/$/, "");
  const publicLink = `${base}/invoices/public/${invoice.id}`;
  const clientName = invoice.client?.name || invoice.client?.email || "Client";
  const senderName = invoice.user?.settings?.companyName || invoice.user?.name || "Your vendor";
  const subject = `${senderName} has sent you an invoice: ${invoice.number}`;

  const html = `
    <div style="font-family: system-ui, -apple-system, 'Segoe UI', Roboto, 'Helvetica Neue', Arial; color: #0f172a; background:#f8fafc; padding:24px;">
      <div style="max-width:600px; margin:0 auto; border-radius:16px; overflow:hidden; box-shadow:0 10px 30px rgba(15,23,42,.08); background:#fff;">
        <div style="background:#2563eb; color:#fff; padding:24px;">
          <p style="font-size:13px; letter-spacing:.15em; text-transform:uppercase; margin:0 0 8px;">New invoice</p>
          <h1 style="margin:0; font-size:24px; font-weight:600;">Invoice ${invoice.number}</h1>
        </div>
        <div style="padding:24px; line-height:1.6;">
          <p style="margin:0 0 16px;">Hi ${clientName},</p>
          <p style="margin:0 0 16px;">${senderName} has shared an invoice that is ready to view.</p>
          <div style="margin-bottom:24px;">
            <a href="${publicLink}" style="display:inline-block;width:100%;text-align:center;font-weight:600;padding:12px 0;background:#1d4ed8;color:#fff;border-radius:10px;text-decoration:none;">View Invoice</a>
          </div>
          <p style="margin:0;font-size:14px;color:#475569;">If the button above does not work, copy and paste the link below into your browser:</p>
          <p style="margin:8px 0 0; word-break:break-word; font-size:14px; color:#2563eb;"><a href="${publicLink}" style="color:#2563eb; text-decoration:none;">${publicLink}</a></p>
        </div>
        <div style="border-top:1px solid #e2e8f0; padding:16px 24px 24px; font-size:12px; color:#94a3b8; text-align:center;">
          This email was generated by gginvoice
        </div>
      </div>
    </div>
  `;

  const text = `Invoice ${invoice.number}\n\nView the invoice here: ${publicLink}`;

  return { subject, html, text };
}



